### ISSUE TITLE
When user configs external file url, if missing "/" or "\" add it for them

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/func_adl_server#8]
THis mistake has caused so many problems.

```
func_adl:
  # This will keep pre-generated C++ around between invocations
  cpp_cache: /C/Users/gordo/Documents/Code/IRIS-HEP/func-adl-server-cache/cpp
  # Results of the query calculations
  results:
    cache: /C/Users/gordo/Documents/Code/IRIS-HEP/func-adl-server-cache/results
    # Define this so that the web server will return a local version of the path to the results.
    # Makes it possible to do a local file open for results. The most obvious thing is to
    # prefix the cache with "file://" on linux/mac and "file:///" on windows. Below is an example
    # from windows.
    local_machine_prefix: file:///C:\Users\gordo\Documents\Code\IRIS-HEP\func-adl-server-cache\results\

```

That local machine prefix thing - needs to be able to deal with a missing trailing "/" or similar.
